### ISSUE TITLE
object file

### ISSUE THREAD

**Issue by unnamed333user** [dingdingcai/GSPose#2]
hi @dingdingcai 
I saw that the object file after generating from Gaussian Splatting is poincloud. 
Where can I get the mesh file of the object ?

**Comment by dingdingcai** [comment]
Hi, thanks for your interest. 
As described in the last subsection of Section 3.1 in the main paper, we represent the reconstructed object as a set of 3D Gaussians which can be viewed as a point cloud.  Each point represents a 3D Gaussian with parameterized color, scale, rotation, opacity, and spherical harmonic coefficients.  So, there is no mesh model. Reconstructing a 3D mesh object from a 3D Gaussian model is out of the scope of the current work.
