### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by unnamed333user** [dingdingcai/GSPose#3]
hi @dingdingcai 
Can you tell me how i can get the files in the demo_data folder ? arposes.txt, frames.txt and so on ?
which app did you use ?

**Comment by dingdingcai** [comment]
Hi,
Please check the demo example provided (under the notebook directory), which includes the information about the demo_data and the data capture app (OnePose Cap from OnePose++)

**Comment by PannagaS** [comment]
How to generate this custom dataset **without** using app?

**Comment by BitStrawber** [comment]
Same question, how can I generate custom dataset based on my own video
