### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by colin-de** [dingdingcai/GSPose#4]
Thanks for the great work! During inference, I could not find this file `bop_dataset/lm/test/000001/test.txt `https://github.com/dingdingcai/GSPose/blob/d499383d0cf345f6c7a958b622ec9da119562b33/dataset/inference_datasets.py#L422 could you please help with this issue?

**Comment by dingdingcai** [comment]
Hi,
Thanks for your interest in our work. You can download and uncompress the data splitting file [lm_train_test_split.zip](https://drive.google.com/drive/folders/1glLdRoN0mS3jP8UM8ZAYo9XqsJiCnUON?usp=sharing) of LINEMOD.
